### ISSUE TITLE
Asociar atributo in_out a la terna indicator-metric-indicator_type

### ISSUE THREAD

**Issue by passcual** [IAMCorporativos/ancar#105]
Según la reunión mantenida con la D.G. de Planificación el 13-10-2016, la condición de dato de entrada/salida no depende sólo del par indicador-métrica, sino también del proceso o subproceso considerado. Se puede dar, además, el caso de que un mismo par indicador-métrica sea considerado de entrada del proceso y de salida del suproceso.
Inicialmente, habíamos incluido la columna in_out en la tabla metrics.
Se requiere revisión del modelo y su impacto, en su caso, en vista y controlador.

**Comment by palomahnhp** [comment]
Lo cierro, ya en Producción
