### ISSUE TITLE
Mantenimiento de tablas maestras 

### ISSUE THREAD

**Issue by palomahnhp** [IAMCorporativos/ancar#3]
Se requiere mantenimiento de las tablas y carga inicial con los datos que nos ha proporcionado el usuario. 
Procesos - Mainprocess
Subprocesos - Subprocess 
Tareas - Task

**Comment by palomahnhp** [comment]
He mergeado en master el muevo diseño del modelo de tablas maestras con los cambios que habíamos comentado y además cambiando el nombre de las tablas de organizaciones y unidades. Ahora creo que queda mucho mas claro.  Por tanto antes de continuar con el resto del diseño de BD y las cargas iniciales haz un merge con master

**Comment by passcual** [comment]
Ok curranta :-)

**Comment by palomahnhp** [comment]
Mergeado
